### ISSUE TITLE
[Bug]: Android Syncing turns Contents into Base64

### ISSUE THREAD

**Issue by focccus** [remotely-save/remotely-save#66] opened 2022-03-31 19:05 UTC
### What happened?

I am not quite sure if this is a problem with the plugin running on Android or with my specific setup, any help is appreachiated.

It seems like when the Android version uploads a new file, it is encoded in Base64, small example:
```md
Tags: #Test | Related: [[T]]
# Test
Lorem Ipsum test
```
```
VGFnczogI1Rlc3QgfCBSZWxhdGVkOiBbW1RdXQojIFRlc3QKTG9yZW0gSXBzdW0gdGVzdA==
```
Sadly this also applies to the metadata json, so sometimes the entire plugin just breaks.
Maybe it is also worth mentioning that Android seems to always download all files , it takes very long, idk if it is related.

## My setup
One issue could also be that I open the vault from the Onedrive Folder on Windows directly and let it sync via built in onedrive between multiple Windows machines as well as the plugin.

Overall this is a very nice plugin, but in this state it is quite unusable.

### What OS are you using?

Windows, Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.14

### Version of Obsidian

0.14.2 / 1.1.1 Android

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment] 2022-03-31 23:09
> One issue could also be that I open the vault from the Onedrive Folder on Windows directly and let it sync via built in onedrive between multiple Windows machines as well as the plugin.

That might be the root case of that “Android seems to always download all files”. Because the windows onedrive client might change the last modified time over and over again. But it’s not the case of the base64 problem.

Likely to be a dup of https://github.com/remotely-save/remotely-save/issues/64

I will try to reproduce the issue firstly…

**Comment by fyears** [comment] 2022-03-31 23:14
And, after uploading file from android to onedrive, would you please check out and download the file directly from onedrive webpage, to see is it normal or not? And what is the line ending and encoding of the downloaded file? Thabks!

**Comment by focccus** [comment] 2022-04-01 10:42
Mhh the windows client could cause the modified time problem yes, although usually it is relatively accurate in terms of that, Idk maybe you also have an extra system that overrides the Onedrive one.

For the encoding, it is simply UTF-8 with CRLF line endings as all my other files, but still in Base64 on the webpage:
[Test.md](https://github.com/remotely-save/remotely-save/files/8396913/Test.md)

**Comment by focccus** [comment] 2022-04-01 10:52
I also just checked after syncing again, the file is also unusable on Android, so it does seem to be something in the upload process ,not how Android encodes the file.

**Comment by fyears** [comment] 2022-04-01 16:05
I can reproduce the error on Android, but the same code runs correctly on iOS and Windows...

Anyway, I used another way to workaround the issue, and tested successfully on Android.

Please checkout the new version: https://github.com/remotely-save/remotely-save/releases/tag/0.3.15

I am closing this issue now since the bug SHOULD be fixed. But feel free to reopen it again if the same issue still stays.

**Closed by fyears** 2022-04-01 16:05 UTC
Labels: bug

**Comment by fyears** [comment] 2022-04-01 16:09
Unfortunately, you have to clear the corresponding vault folder on OneDrive (using web page), and start the sync from the beginning.

**Comment by focccus** [comment] 2022-04-01 17:54
Okay thank you very much for the quick fix,
I'll try that and report later, thanks
