### ISSUE TITLE
[Bug]: Error when trying to sync vault with E2E encryption 

### ISSUE THREAD

**Issue by TomYeoman** [remotely-save/remotely-save#737] opened 2024-07-03 19:42 UTC
### What happened?

<img width="1410" alt="image" src="https://github.com/remotely-save/remotely-save/assets/14075632/1ac7e566-7370-4c49-ac00-4bb4b7d79d1b">

I have saved a drive on windows, setting a password. I can confirm I can see the folder with encrypted files at in Apps/remotely-save/<vault-name> 

After going on to my mac
- Create new local directory, matching name of remote
- Setup remotely save, setting same password
- Try to sync

I get the error shown in the screenshot. If I set no password on the mac side, I pull the encrypted files, so the connection is definitely OK. 

### What OS are you using?

Windows, macOS

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.5.12

### Version of Obsidian

1.6.5

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment] 2024-07-05 10:40
go to onedrive website, is there any unencrypted files inside `/Apps/remotley-save/<vault name>`?

**Comment by TenTakano** [comment] 2024-07-07 18:26
I have same issue with Ubuntu 22.04 and Windows, iPhone. I'm using R1 for storage to sync.In my situation, the encrypted files are stored in R1 bucket including .obsidian folder because I'm using option for synchronizing config. There are no failure with no password but it occurs extracting encrypted files directly. In addition, I'm also facing anothor issue which the original local vault (this is stored in Ubuntu 22.04) cannot sync to remote after once closing obsidian. From these phenomenons, I guess there are some issues on encrypt/decrypt modules.

**Comment by fyears** [comment] 2024-07-08 10:12
go to r2 website, is there any unencrypted files inside uour encrypted vault?

**Comment by TenTakano** [comment] 2024-07-08 13:24
> go to r2 website, is there any unencrypted files inside uour encrypted vault?

No. All files are encrypted.
But somehow, I tried once again with another bucket, successfully synchronized with Ubuntu and Windows. The vault which is used to verification is same as last post. All I have done is just change encrypt password and bucket name.

**Comment by fyears** [comment] 2024-07-18 15:45
so is the issue still consistently reproducible now?

**Comment by TenTakano** [comment] 2024-07-20 03:16
I could resolve the issue in my case.

**Comment by fyears** [comment] 2024-07-20 06:54
if a consistent reproducible step is found, please post it here and you are welcome to re open the issue

**Closed** 2024-07-20 06:54 UTC
Labels: bug
