### ISSUE TITLE
[Bug]: 'Incremental Push And Delete' does not delete folder in remote

### ISSUE THREAD

**Issue by obsidianmduser** [remotely-save/remotely-save#708] opened 2024-06-16 22:42 UTC
### What happened?

I have tested new feature 'Incremental Push And Delete' (thanks for implementation) and I have noticed that folder deletion in Android Obsidian app does not delete folder in remote (Dropbox) after sync has finished it's job.

File deletion worked (deleted in app -> deleted in remote).

### What OS are you using?

Android

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

Dropbox

### Version of the plugin

0.5.7

### Version of Obsidian

1.6.3

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment] 2024-06-17 02:06
please export the sync plan and see the item of that folder.

https://github.com/remotely-save/remotely-save/blob/master/docs/how_to_debug/export_sync_plans.md

**Comment by fyears** [comment] 2024-06-17 13:28
yeah but still please consider exporting the sync plan so that i can double confirm. folder deletion is harder than file deletion actually

**Comment by fyears** [comment] 2024-06-17 14:04
or if you close the dropbox official client, does the bug disappear?

**Comment by fyears** [comment] 2024-06-17 17:36
> First content is deleted and then empy folder is deleted – noticed this while purging deleted files out of Dropbox trash bin. Cannot be this done by deleting folder and it's content all in one "transaction"?

No. Because not always all files are deleted together inside one folder. So the algorithm just try to delete the files and folders one by one.

> it actually created /Apps/remotely-save/${vault_name}.

That's the special situation because the plugin always guess the remote vault folder (empty or not) exists. If the files are not uploaded then the behavior is expected.

**Comment by fyears** [comment] 2024-06-17 17:37
So anyways your original issue is identified and obviously cannot be fixed in the plugin side. The issue is closed now. Thanks for your detailed report!

**Closed by fyears** 2024-06-17 17:37 UTC
Labels: bug
