### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by KurKuza** [remotely-save/remotely-save#240] opened 2022-11-06 18:16 UTC
### What feature are you suggesting?

is it possible to sync via google drive?

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by rnd256** [comment] 2022-12-19 22:58
Duplicate of https://github.com/remotely-save/remotely-save/issues/4.

**Comment by fyears** [comment] 2023-12-17 15:17
Duplicate of https://github.com/remotely-save/remotely-save/issues/4.

**Closed by fyears** 2023-12-17 15:17 UTC
Labels: enhancement
