### ISSUE TITLE
[Bug]: Error while syncing new files on iOS to Backblaze B2

### ISSUE THREAD

**Issue by n0k0m3** [remotely-save/remotely-save#70] opened 2022-04-09 13:19 UTC
### What happened?

- Create a new notes, or delete notes on iOS
- Sync to B2
- Error as in image
![IMG-0026](https://user-images.githubusercontent.com/10925298/162575702-22b91565-aca0-4be4-a879-32912e76ac69.PNG)

- Checked on PC, no errors while syncing with creating/deleting new notes

### What OS are you using?

Linux, iOS (iPhone, iPad), Android

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.17

### Version of Obsidian

1.1.1 (iOS), 0.14.2 (Linux)

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment] 2022-04-09 13:35
hmm… thanks for your report. let me try to reproduce the error firstly. 

btw, have you enabled the “bypass cors locally” setting?

**Comment by fyears** [comment] 2022-04-09 13:36
I personally use another s3 provider and never saw this kind of error before…

**Comment by n0k0m3** [comment] 2022-04-09 13:39
Yes I used bypass cors locally on both iOS and PC

**Comment by n0k0m3** [comment] 2022-04-09 13:39
maybe just isolated to B2. B2 is free up to 10gb so you can test this out easily.
Also what S3 provider you are using? AWS?

**Comment by fyears** [comment] 2022-04-10 09:46
I could reproduce the error. It was because of an inconsistency between mobile and desktop. Fixed in https://github.com/remotely-save/remotely-save/releases/tag/0.3.18 . Please upgrade the plugin and try again. Thanks!

**Closed by fyears** 2022-04-10 09:46 UTC
Labels: bug
