### ISSUE TITLE
[Bug]: Remove my local file unexpect when using S3 compatibility mode

### ISSUE THREAD

**Issue by kevin1sMe** [remotely-save/remotely-save#72] opened 2022-04-10 15:17 UTC
### What happened?

I had using `remotely-save` for many days, it's work.
When I refactor my Obsidian directory and move assets to another directory then sync it using `Remotely Save`  manual， SOME OF  MY assets( picture & audio) deleted.

I export the plan log:
 ```log
 "_assets/2017-09-06-MongoDB-Architecture.jpg": {
      "key": "_assets/2017-09-06-MongoDB-Architecture.jpg",
      "deltimeRemote": 1649516470571,
      "deltimeRemoteFmt": "2022-04-09T23:01:10+08:00",
      "existLocal": false,
      "existRemote": false,
      "decision": "keepRemoteDelHist",
      "decisionBranch": 7
    },
...
```
I move file `2017-09-06-MongoDB-Architecture.jpg` to `_assets/2017-09-06-MongoDB-Architecture.jpg`。
Why `existLocal` is false? 

### What OS are you using?

macOS

### What remote cloud services are you using?

S3

### Version of the plugin

0.3.18

### Version of Obsidian

v0.14.2

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment] 2022-04-11 04:30
I am sorry to hear that! Hope you have backed up the files somewhere else....

Anyway, regarding the question you asked:

1. how to debug

    Open the console of Obsidian (should be ctrl+shift+i on Windows, might be cmd+opt+i on Mac).

    Here we can input some js code and see the result.

    Also, we can use the **Obsidian command palette** and invoke the "Start sync (dry run only)" command to generate the sync plan again **without actual sync** (so this command is safe to run and not actually affect any files).

    
    ![1649651197(1)](https://user-images.githubusercontent.com/1142836/162665116-38a37c89-fbe5-42ae-a814-48bf21d512b5.png)


2. `existLocal` problem

    Would you like to input this and see the output of this function in the console?

    ```js
    app.vault.getAllLoadedFiles().map(x=>x.path)
    ```

    The `existLocal` strictly relies on the output of the above function. If the function returns the file, then `existLocal=true`. I guessed that, after you move the files, Obsidian might need a while to refresh the list...

    If you find out anyfile that is in the list but shows up `exitLocal=False` in the list, then that's a bug in Remotely Save.

3. the deletion problem

    Furthermore, as you may notice, you have deleted the file on the other device before, so that `deltimeRemote(Fmt)` is not empty, so the deletions is unfortunately applied to the current device as well.

**Comment by kevin1sMe** [comment] 2022-04-11 14:02
Thanks for your reply.

I have check the `existLocal` follow your guide.
```json
  "_assets/2017-09-06-MongoDB-Architecture.jpg": {
      "key": "_assets/2017-09-06-MongoDB-Architecture.jpg",
      "existLocal": true,
      "mtimeLocal": 1648793066000,
      "mtimeLocalFmt": "2022-04-01T14:04:26+08:00",
      "sizeLocal": 49454,
      "existRemote": false,
      "deltimeRemote": 1649516470571,
      "deltimeRemoteFmt": "2022-04-09T23:01:10+08:00",
      "decision": "keepRemoteDelHist",
      "decisionBranch": 7
    },
```
As you mentioned, the file exist locally and deltimeRemote is non-empty. But I can't remember I had delete operations, what I did was rename folders or move files operations. Maybe it's a multi-client problem?

Is  it caused by unexpect delete and `deltimeRemote` is newer than `mtimeLocal`?  I thought that if I modify the mtime of the file, it can skip the judgment & skip delete it.  But after I modify the mtime of the file through the touch command, I repeat the previous steps again, and the original result is still obtained. The mtime of this file has not been modified.

the ls command show this:
```bash
❯ stat -f "%c %m %a" _assets/2017-09-06-MongoDB-Architecture.jpg
1649684910 1649684910 1649685212
❯ ls -ltr _assets/2017-09-06-MongoDB-Architecture.jpg
-rw-r--r--@ 1 kevin  staff  49454  4 11 21:48 _assets/2017-09-06-MongoDB-Architecture.jpg
```
And sync plan show this:
```json
  "_assets/2017-09-06-MongoDB-Architecture.jpg": {
      "key": "_assets/2017-09-06-MongoDB-Architecture.jpg",
      "existLocal": true,
      "mtimeLocal": 1648793066000,
      "mtimeLocalFmt": "2022-04-01T14:04:26+08:00",
      "sizeLocal": 49454,
      "existRemote": false,
      "deltimeRemote": 1649516470571,
      "deltimeRemoteFmt": "2022-04-09T23:01:10+08:00",
      "decision": "keepRemoteDelHist",
      "decisionBranch": 7
    },
```

So what can I do ?

**Comment by fyears** [comment] 2022-04-11 16:37
> But I can't remember I had delete operations, what I did was rename folders or move files operations. Maybe it's a multi-client problem?

If A is renamed to B, A is marked deleted and B is marked created.

> Is it caused by unexpect delete and deltimeRemote is newer than mtimeLocal? I thought that if I modify the mtime of the file, it can skip the judgment & skip delete it.

You are totally right! And the new file should be uploaded then.

> So what can I do ?

There are 2 ways, you can try the first one firstly, and if failed, try the second one.

1. The first way: try the linux command `touch file.md` which should update the mtime locally. Then restart the Obsidian, then **dry run sync** (not actually sync!) again. If you see a larger mtimeLocal, then the problem is solved!
2. The second way: 

    Please read through the following text before you take any actions.
    
    All deletion operations are recorded on the remote file `_remotely-save-metadata-on-remote.json`. If your s3 provider has some web pages for you to manage the files, you can directly go to the web page and delete the file `_remotely-save-metadata-on-remote.json` and try the dry run sync again.
    
    Please be aware that, by deleting the json file, ALL deletions info are lost, **across all devices!**

    For example, assuming you have deleted file X on device 1, but not on device 2. Then you run the sync on device 2. Then the plugin will upload the file X on device 2 again because it doesn't know the file X was deleted before. Then you run the sync on device 1, the plugin will download the file X from s3 because the file X has a larger mtime remotely... To avoid this, you have to manually delete the file X on device 2 before syncing device 2.

**Comment by kevin1sMe** [comment] 2022-04-13 14:06
Follow your suggestions, but sorry to say that NOT solved.

After using `touch -m`, the modify time of the file is updated on the OS, but the `mtimeLocal` displayed by remote save is still wrong.

I restart Obsidian & restart Mac, and still not help. 

---
Obsidian: 0.14.5 (updated recently)
Remotely Save: 0.3.18
MacOS: 12.3

Could I debug myself in obsidian? Some reference about debug? Thanks

**Comment by kevin1sMe** [comment] 2022-04-13 14:16
<img width="737" alt="image" src="https://user-images.githubusercontent.com/6886076/163200699-48e5697a-ae70-4389-bf0e-8a9f3c0de817.png">

<img width="839" alt="image" src="https://user-images.githubusercontent.com/6886076/163200981-4360fbcc-3d3f-4246-b84f-e2dd3921bc57.png">

**Comment by fyears** [comment] 2022-04-13 14:17
If the two commands above do not return the correct mtime as your macOS, then here is a bug of Obsidian, then you should report it on the Obsidian forum.

If you find the commands return the correct value, but not the same is remotely-save's `mtimeLocal`, then here is a bug of remotely-save...

**Comment by kevin1sMe** [comment] 2022-04-13 14:19
<img width="727" alt="image" src="https://user-images.githubusercontent.com/6886076/163201496-c8a17d23-bbbd-4310-ab31-7db1ce08b9b7.png">

Thank you.

**Comment by kevin1sMe** [comment] 2022-04-15 14:49
I'm sorry for the late reply. Here is the log:

```log
[pos1], _assets/2017-09-06-MongoDB-Architecture.jpg, mtimeLocal=1649855436047, mtime=1649855436047, ctime=1648793066000
VM142:226 [pos2], _assets/2017-09-06-MongoDB-Architecture.jpg, mtimeLocal=1649855436047
VM142:226 [pos3], 编程语言/golang/2017-09-06-MongoDB-Architecture.jpg, mtimeLocal=undefined
VM142:226 [pos3], 技术/golang/2017-09-06-MongoDB-Architecture.jpg, mtimeLocal=undefined
VM142:226 [pos3], 00assets/2017-09-06-MongoDB-Architecture.jpg, mtimeLocal=undefined
VM142:226 [pos3], _assets/2017-09-06-MongoDB-Architecture.jpg, mtimeLocal=1649855436047
VM142:226 [pos3], assets/2017-09-06-MongoDB-Architecture.jpg, mtimeLocal=undefined
VM142:226 [pos3], 技术/2017-09-06-MongoDB-Architecture.jpg, mtimeLocal=undefined
```
Next log is `sync-plan-log`:

```json
{
    "_assets/2017-09-06-MongoDB-Architecture.jpg": {
    "key": "_assets/2017-09-06-MongoDB-Architecture.jpg",
    "existLocal": true,
    "mtimeLocal": 1648793066000,
    "mtimeLocalFmt": "2022-04-01T14:04:26+08:00",
    "sizeLocal": 49454,
    "existRemote": false,
    "deltimeRemote": 1649516470571,
    "deltimeRemoteFmt": "2022-04-09T23:01:10+08:00",
    "decision": "keepRemoteDelHist",
    "decisionBranch": 7
  }, 
  "编程语言/golang/2017-09-06-MongoDB-Architecture.jpg": {
    "key": "编程语言/golang/2017-09-06-MongoDB-Architecture.jpg",
    "deltimeRemote": 1649492539193,
    "deltimeRemoteFmt": "2022-04-09T16:22:19+08:00",
    "existLocal": false,
    "existRemote": false,
    "decision": "keepRemoteDelHist",
    "decisionBranch": 7
  },
  "技术/golang/2017-09-06-MongoDB-Architecture.jpg": {
    "key": "技术/golang/2017-09-06-MongoDB-Architecture.jpg",
    "deltimeRemote": 1649500747875,
    "deltimeRemoteFmt": "2022-04-09T18:39:07+08:00",
    "existLocal": false,
    "existRemote": false,
    "decision": "keepRemoteDelHist",
    "decisionBranch": 7
  },
  "00assets/2017-09-06-MongoDB-Architecture.jpg": {
    "key": "00assets/2017-09-06-MongoDB-Architecture.jpg",
    "deltimeRemote": 1649516486033,
    "deltimeRemoteFmt": "2022-04-09T23:01:26+08:00",
    "existLocal": false,
    "existRemote": false,
    "decision": "keepRemoteDelHist",
    "decisionBranch": 7
  },
 "assets/2017-09-06-MongoDB-Architecture.jpg": {
      "key": "assets/2017-09-06-MongoDB-Architecture.jpg",
      "deltimeRemote": 1649600397540,
      "deltimeRemoteFmt": "2022-04-10T22:19:57+08:00",
      "existLocal": false,
      "existRemote": false,
      "decision": "keepRemoteDelHist",
      "decisionBranch": 7
    },

    "技术/2017-09-06-MongoDB-Architecture.jpg": {
        "key": "技术/2017-09-06-MongoDB-Architecture.jpg",
        "deltimeRemote": 1649501651490,
        "deltimeRemoteFmt": "2022-04-09T18:54:11+08:00",
        "existLocal": false,
        "existRemote": false,
        "decision": "keepRemoteDelHist",
        "decisionBranch": 7
      }
 ...
}
```

You can see I had move the picture from one to another. Then the mtime is not correct.

**Comment by fyears** [comment] 2022-04-16 13:27
Still no clues... Initially the mtime was correct but in the end the value was changed...

Would you like to contact (send direct message to) me on discord `fyears#3888` or obsidian forum `fyears`?

**Comment by fyears** [comment] 2022-04-17 16:24
After debugging, the issue comes from that the sync plan was not updated in dry run mode. this bug is fixed in https://github.com/remotely-save/remotely-save/commit/13537d1481c71335616d499a39279d57a6b4c944

**Closed by fyears** 2022-04-17 16:24 UTC
Labels: bug
