### ISSUE TITLE
[Bug]: Deleted files or folders resurrected

### ISSUE THREAD

**Issue by Barmaid1076** [remotely-save/remotely-save#611] opened 2024-04-17 12:34 UTC
### What happened?

Cannot delete files and folders sometimes (BY SOMETIIMES I MEANT IT HAPPENS A LOT), the deleted file or folders somehow get regenerated.

Deleting a file doesn't delete it on my webdev server

Possible cause: I use this plugin on 3 devices, windows, iphone and ipad

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

webdav

### Version of the plugin

latest

### Version of Obsidian

latest

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [x] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment] 2024-04-17 16:15
are you doing some operations concurrently on the same folder on the multiple devices?

且可以用中文反馈

**Comment by Barmaid1076** [comment] 2024-04-17 21:49
在这些情况发生的时候没有同时操作同一个文件, 
但是之前有过好奇尝试两个设备同时修改同一个文件, 结果就是一个文件把另一个文件覆盖了，没有出现任何错误

**Comment by seyeeL** [comment] 2024-04-20 02:37
我也没有两边都操作更新

**Comment by nallebrean** [comment] 2024-04-24 20:19
I suspect it has something to do with links. I got the feeling that files that are linked alot are more likely to be recreated. But it doesn't really make sense to me. There are still only an erased file. Both the correct and the dobble one are pointing to correct files.

**Comment by fyears** [comment] 2024-04-30 07:49
Please consider report the sync plans on each device. I suspect you still update something on one device.

**Comment by nallebrean** [comment] 2024-04-30 14:33
You mean that obsidian are still working on something simultaneously with the sync?

**Comment by nallebrean** [comment] 2024-05-01 18:01
That has happened as well. To get around it, I moved a few files at a time
and it worked on device Y. However, it did not work later on device Z.

Den ons 1 maj 2024 19:55JK2333 ***@***.***> skrev:

**Comment by fyears** [comment] 2024-05-02 03:09
may i ask anyone reproduce the error using a **new, only installing remotely save, test vault** and then upload sync plans? remember to remove any sensitive personal info

**Comment by nallebrean** [comment] 2024-05-05 12:54
The problem seems to be with the "Deletion Destination". When it's set to "system default (default)", it works, but when set to "Obsidian .trash folder", the files are NOT moved from the corresponding disk folder, and I suppose the RS-sync just reads them back. See my attached PDF with screenshots.

[Debug remote save 20240505.pdf](https://github.com/remotely-save/remotely-save/files/15213000/Debug.remote.s
[Android Test 2 sync_plans_hist_exported_on_17149
[Win Test 2 sync_plans_hist_exported_on_1714912201793.md](https://github.com/remotely-save/remotely-save/files/15213009/Win.Test.2.sync_plans_hist_exported_on_1714912201793.md)
[Win Test 1 sync_plans_hist_exported_on_1714911209855.md](https://github.com/remotely-save/remotely-save/files/15213010/Win.Test.1.sync_plans_hist_exported_on_1714911209855.md)
11982412.md](https://github.com/remotely-save/remotely-save/files/15213006/Android.Test.2.sync_plans_hist_exported_on_1714911982412.md)
[Android Test 1 sync_plans_hist_exported_on_1714911177987.md](https://github.com/remotely-save/remotely-save/files/15213007/Android.Test.1.sync_plans_hist_exported_on_1714911177987.md)
ave.20240505.pdf)

**Comment by 2019YKL** [comment] 2024-05-05 16:15
现在多端更新简直是灾难，删除了文件还会出现，移动了文件又会重新生成到移动前的位置

**Comment by nallebrean** [comment] 2024-05-05 16:20
Quick temporary fix is to set the removed file setting to default!

Den sön 5 maj 2024 18:15JK2333 ***@***.***> skrev:

**Comment by 2019YKL** [comment] 2024-05-05 16:31
I always set it to the default value, which doesn't seem to be the cause of the bug.

**Comment by 2019YKL** [comment] 2024-05-05 16:33
I've tested this several times and found that deleting a file on Mac/window doesn't remove the same file on the Ipad, and then a certain sync will sync the ipad's wrong file up again so that the version goes back down again.

**Comment by fyears** [comment] 2024-05-05 17:18
> I've tested this several times and found that deleting a file on Mac/window doesn't remove the same file on the Ipad

are you using auto sync? after deleting a file on windows has the deletion synced on remote (eg. onedrive website)? 

@2019YKL

**Comment by nallebrean** [comment] 2024-05-05 17:19
It's strange that the Obsidan didn't move the files on the A client when I
remove them. An obsidan bug? The removed file setting in RS should not
really makes a different on the A client. Only on the B client when files
has been synced as removed.

Den sön 5 maj 2024 18:32JK2333 ***@***.***> skrev:

**Comment by fyears** [comment] 2024-05-05 18:32
@nallebrean @2019YKL @Barmaid1076 @seyeeL 

------------------------------------------------------------------------------

Don't need to guess. Please follow the steps **precisely**, and see any step doesn't return the same result as my description. Please, really **precisely**, do not do anything more or less.

1. Windows
    1. On Windows, create new vault naming "testvault"
    2. On Windows, Obsidian should create a default file "Welcome.md".
    3. On Windows, create new folder "testfolder1", create new file inside the folder "testfolder1/testfile1.md". Write something into that md file.
    4. On Windows, install remotely save
    5. On Windows, configure webdav (I use infinicloud). DO NOT TOUCH any other settings!!!! No setting password, not setting auto run, and deletion destination by default should be system trash.
    6. On Windows, sync

2. infinicloud website
    1. go to infinicloud website, check these are generated: folder testvault, folder testvault/testfolder1, file testvault/testfolder1/testfile1.md, file testvault/Welcome.md. The expected behaviour is that all of them are generated.

3. iphone
    1. On iphone, create new vault naming "testvault"
    2. On iphone, Obsidian should create a default file "Welcome.md".
    3. On iphone, install remotely save
    4. On iphone, configure webdav (I use infinicloud). DO NOT TOUCH any other settings!!!! No setting password, not setting auto run, and deletion destination by default should be system trash.
    5. On iphone, sync
    6. On iphone, check all these are generated in the vault: folder testfolder1, file testfolder1/testfile1.md, file Welcome.md. The expected behaviour is that all of them are generated.

4. windows
    1. On Windows, delete the folder testfolder1
    2. On Windows, sync
    3. On Windows, the sync should fail, because of the deletion protection
    4. On Windows, change the remotely save settings "Abort Sync If Modifications Above Percentage" to "100% (disable the protection)".
    5. On Windows, sync
    6. The sync should succeed.

5. infinicloud website
    1. go to infinicloud website, **check these are deleted or not: folder testvault/testfolder1 and file testfolder1/testfile1.md**. The expected behaviour is that all of them are deleted.

6. iphone
    1. On iphone, sync
    2. On iphone, the sync should fail, because of the deletion protection
    3. On iphone, change the remotely save settings "Abort Sync If Modifications Above Percentage" to "100% (disable the protection)".
    4. On iphone, sync
    5. The sync should succeed.
    6. On iphone:  **check these are deleted or not: folder testvault/testfolder1 and file testfolder1/testfile1.md**. The expected behaviour is that all of them are deleted.




---------------------------------------------------------------------


不需要猜测。请**完全按照**以下步骤操作，看看哪一步操作结果和我的描述不一样。请注意，**完全按照**，不要做多了，不要做少了。

1. Windows
    1. Windows 创建新的库，库名字叫做 testvault
    2. Windows 里 Obsidian 自动在新的库创建了 Welcome.md 文件。
    3. Windows 创建文件夹 testfolder1 ，文件夹里创建文件 testfolder1/testfile1.md，随便写点东西
    4. Windows 安装 remotely save
    5. Windows 设置 webdav。我用 infinicloud。**不要修改其他任何设置！！！**不设置密码，不设置自动运行，删除目的地默认是系统回收站。
    6. Windows 触发同步。

2. infinicloud 网站

    1. 去 infinicloud 网站，检查 testvault文件夹是否有生成，testvault/testfolder1 文件夹是否有生成，testvault/testfolder1/testfile1.md 是否有生成，testvault/Welcome.md 是否有生成。期待行为是所有都生成了。

3. iphone
    1. 打开 iphone Obsidian，创建新的 vault，名字叫 testvault
    2. iphone Obsidian 自动在新的库创建了 Welcome.md 文件。
    3. iphone obsidian 安装 remotely save
    4. iphone obsidian 设置 webdav。我用 infinicloud。**不要修改其他任何设置！！！**不设置密码，不设置自动运行，删除目的地默认是系统回收站。
    5. iphone 触发同步
    6. 检查 iphone obsidian 的 valut 内是不是生成了：testfolder1 文件夹，testfolder1/testfile1.md 文件，Welcome.md 文件

4. windows
    1. windows ，删除 testfolder1 文件夹
    2. windows 触发同步
    3. windows 应该触发了保护，同步失败
    4. windows 的 remotely save 设置，修改删除保护为 100%，也即，去除保护
    5. windows 触发同步
    6. 这时候应该同步成功了

5. infinicloud 网站
    1. 去 infinicloud 网站，**检查 testvault/testfolder1 文件夹是不是已经被删除了**，期待行为是被删除了

6. iphone
    1. iphone 触发同步
    2. iphone 应该触发了保护，同步失败
    3. iphone 的 remotely save 设置，修改删除保护为 100%，也即，去除保护
    4. iphone 触发同步
    5. 这时候应该同步成功了
    6. 检查 iphone obsidian 的 **vault 内的 testfolder1 是不是被删除了**，期待行为是被删除了。

**Comment by nallebrean** [comment] 2024-05-05 19:50
Sorry but what will "Server Adress" be for infinicloud?

**Comment by 2019YKL** [comment] 2024-05-06 01:07
我使用的是S3阿里云服务。我采取了以下措施来尝试正常同步，在所有的设备中，我下方的设置是一致的。

<img width="810" alt="image" src="https://github.com/remotely-save/remotely-save/assets/51532948/cb6b908d-fe12-4a6c-b698-3f44af42c0e6">
关掉自动运行

<img width="801" alt="image" src="https://github.com/remotely-save/remotely-save/assets/51532948/df0cae7a-1ec2-4b4b-bd9d-e7efb463339a">
设置垃圾文件目标文件夹为系统回收站

<img width="796" alt="image" src="https://github.com/remotely-save/remotely-save/assets/51532948/289dfad6-c9c1-441e-8c7d-334470d2ae00">
全部关闭精准修改时间

现在我的行为如下：

<img width="1216" alt="image" src="https://github.com/remotely-save/remotely-save/assets/51532948/041f04ba-5ed8-4d2e-90ee-c74029b872ab">


Mac删除Inbox所有文件，手动同步，查看S3存储桶文件变化，文件被删除，与预期一致。

创建一个文件夹，新建文件，尝试同步，文件被新增，与预期一致。

<img width="296" alt="image" src="https://github.com/remotely-save/remotely-save/assets/51532948/2682c6f3-2e2a-49b4-8c12-52389aafb01a">

此时S3的存储桶 Inbox下只有一个测试.md文件。

前往iPad同步，iPad无法正常同步，没有创建新文件，也没有删除旧文件。

同步阶段一直显示如下日志，但同步的文件一直在变动，即时我根本没有改动这些文件。

```
Remotely Save 正处于此阶段：触发 manual。

running！中断
syncing progress=1377/1074,decision=conflict_modif ied_then_keep_remote,path=02 Area/B
12/2022/2022-11-17.md, source=manual
```

这个时候，Ipad的同步其实一直是没有完成的阶段，但是能把已经删除的文件上传上去，并且不会删除旧文件

<img width="1192" alt="image" src="https://github.com/remotely-save/remotely-save/assets/51532948/8d54bac8-6051-4719-b1a9-0b261aaafa34">

这时候，存储桶重新被写入，Mac手动同步后，重新拉取了Mac上一个版本就删除的全部文件。于是同步出现问题。

抱歉我没办法新开一个库来测试，但是我已经按您的要求修改了下方几个要点

- 创建新文件
- 删除新文件
- 设置保持不自动运行
- 删除目的地为系统回收站
- 手动触发同步

由于Mac/Ipad之间的同步都无法如期运行，我没有再测试Windows。

**Comment by 2019YKL** [comment] 2024-05-06 01:15
> 在这些情况发生的时候没有同时操作同一个文件,
> 
> 但是之前有过好奇尝试两个设备同时修改同一个其他的markdown文件, 结果就是一个文件把另一个文件覆盖了，没有出现任何错误
> 
> 还有就是删除单个文件的时候有的时候会成功 但是删除文件夹的时候几乎没有成功过, 总是会重新生成

是的，我测试也是如此，删除文件在iPhone和iPad表现不稳定，有时候能正常删除，有时候无法正常删除。

**Comment by fyears** [comment] 2024-05-06 04:58
@2019YKL 

> Mac删除Inbox所有文件，手动同步

删除文件之前，mac和ipad已经进行了完全一致同步了吗？也就是说，那时候之前，mac，ipad，s3 三方是完全一致，内容一致，修改时间一致吗？这是先决条件啊

> 前往iPad同步，iPad无法正常同步，没有创建测试.md新文件，也没有删除我图中打上马赛克的旧文件。

ipad 上导出同步计划然后看看你马赛克的那些被重新上传的文件的信息？是一个大的json片段。可以改掉json内的实际文件名。

> 抱歉我没办法新开一个库来测试

为啥呢，新建一个 vault 会有什么成本？

**Comment by fyears** [comment] 2024-05-06 04:59
> Sorry but what will "Server Address" be for infinicloud? 

@nallebrean please refer the screenshot here https://github.com/remotely-save/remotely-save/tree/master/docs/remote_services/webdav_infinicloud_teracloud

**Comment by 2019YKL** [comment] 2024-05-06 05:27
> 删除文件之前，mac和ipad已经进行了完全一致同步了吗？也就是说，那时候之前，mac，ipad，s3 三方是完全一致，内容一致，修改时间一致吗？这是先决条件啊

不，Mac和s3是一致的，插件可以正常工作。

插件有bug后，我ipad端没有写入/删除文件变动，只是一直在测试Ipad同步。

至于您说的全部一致，是不是先决条件，我并不清楚。

因为现在插件引起的Ipad无法正常同步，我有1700多个文件，我想不到什么办法让它和Mac完全一致。

<img width="852" alt="image" src="https://github.com/remotely-save/remotely-save/assets/51532948/a689c295-d536-4136-8875-05564d126074">

这是我的一部分日志，我导出日志后发现可能是全量变动的，因为记录似乎有几万条。

<img width="617" alt="image" src="https://github.com/remotely-save/remotely-save/assets/51532948/9fce173c-7270-4a9e-a3d8-ad1beb07fd3e">

**Comment by 2019YKL** [comment] 2024-05-06 05:55
我新开了一个库，并只设置了所需的最小信息（服务地址、区域、Access key ID、Secret Access Key、Bucket Name），其他全部保持默认，发现同步问题依旧。

<img width="1060" alt="image" src="https://github.com/remotely-save/remotely-save/assets/51532948/9e9d9fb2-bd7e-4325-a6f5-e6e6ba1d29c6">

我在Mac上有一份创建库新生成的Welcome.md，我第一次使用同步，成功将文件同步上S3，此时Ipad是空库（刚刚创建）

<img width="1181" alt="image" src="https://github.com/remotely-save/remotely-save/assets/51532948/a0bdf045-20b3-4c16-8b27-605548cecf5d">

随后我在Ipad填入所需最小信息，成功拉取S3文件，同步了Welcome。

![IMG_1643](https://github.com/remotely-save/remotely-save/assets/51532948/1f1d6e7b-81f8-4616-b022-99021e2bf5e3)

这时候，我尝试在Mac删除文件，然后手动同步，这时候，S3文件没有被删除，反而还同步回了本地。


https://github.com/remotely-save/remotely-save/assets/51532948/ad4d3a7f-fc19-4844-a1b6-67c452a1c115

视频演示如上。

**Comment by fyears** [comment] 2024-05-06 10:08
@2019YKL 

> 上万份文件不知道如何一致

是的，所以新建测试 vault 来进行

> 然后我尝试在Mac删除文件，然后手动同步，这时候，S3文件没有被删除，反而还同步回了本地。

唉，这里真的，完全按照我的步骤来操作，是否可以呢？关键在于，**有welcome文件的情况下，新建文件夹和里面的文件**，然后做同步和删除。

如果只有一份 welcome 文件，你删除了，本地会变成空库，那么会走到特殊逻辑把远程的文件重新下载，这不是 bug，也和本群的问题无关。

**Comment by fyears** [comment] 2024-05-06 10:10
> 
> 
> @nallebrean @2019YKL @Barmaid1076 @seyeeL 
> 
> 
> 
> ------------------------------------------------------------------------------
> 
> 
> 
> Don't need to guess. Please follow the steps **precisely**, and see any step doesn't return the same result as my description. Please, really **precisely**, do not do anything more or less.
> 
> 
> 
> 1. Windows
> 
>     1. On Windows, create new vault naming "testvault"
> 
>     2. On Windows, Obsidian should create a default file "Welcome.md".
> 
>     3. On Windows, create new folder "testfolder1", create new file inside the folder "testfolder1/testfile1.md". Write something into that md file.
> 
>     4. On Windows, install remotely save
> 
>     5. On Windows, configure webdav (I use infinicloud). DO NOT TOUCH any other settings!!!! No setting password, not setting auto run, and deletion destination by default should be system trash.
> 
>     6. On Windows, sync
> 
> 
> 
> 2. infinicloud website
> 
>     1. go to infinicloud website, check these are generated: folder testvault, folder testvault/testfolder1, file testvault/testfolder1/testfile1.md, file testvault/Welcome.md. The expected behaviour is that all of them are generated.
> 
> 
> 
> 3. iphone
> 
>     1. On iphone, create new vault naming "testvault"
> 
>     2. On iphone, Obsidian should create a default file "Welcome.md".
> 
>     3. On iphone, install remotely save
> 
>     4. On iphone, configure webdav (I use infinicloud). DO NOT TOUCH any other settings!!!! No setting password, not setting auto run, and deletion destination by default should be system trash.
> 
>     5. On iphone, sync
> 
>     6. On iphone, check all these are generated in the vault: folder testfolder1, file testfolder1/testfile1.md, file Welcome.md. The expected behaviour is that all of them are generated.
> 
> 
> 
> 4. windows
> 
>     1. On Windows, delete the folder testfolder1
> 
>     2. On Windows, sync
> 
>     3. On Windows, the sync should fail, because of the deletion protection
> 
>     4. On Windows, change the remotely save settings "Abort Sync If Modifications Above Percentage" to "100% (disable the protection)".
> 
>     5. On Windows, sync
> 
>     6. The sync should succeed.
> 
> 
> 
> 5. infinicloud website
> 
>     1. go to infinicloud website, **check these are deleted or not: folder testvault/testfolder1 and file testfolder1/testfile1.md**. The expected behaviour is that all of them are deleted.
> 
> 
> 
> 6. iphone
> 
>     1. On iphone, sync
> 
>     2. On iphone, the sync should fail, because of the deletion protection
> 
>     3. On iphone, change the remotely save settings "Abort Sync If Modifications Above Percentage" to "100% (disable the protection)".
> 
>     4. On iphone, sync
> 
>     5. The sync should succeed.
> 
>     6. On iphone:  **check these are deleted or not: folder testvault/testfolder1 and file testfolder1/testfile1.md**. The expected behaviour is that all of them are deleted.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> ---------------------------------------------------------------------
> 
> 
> 
> 
> 
> 不需要猜测。请**完全按照**以下步骤操作，看看哪一步操作结果和我的描述不一样。请注意，**完全按照**，不要做多了，不要做少了。
> 
> 
> 
> 1. Windows
> 
>     1. Windows 创建新的库，库名字叫做 testvault
> 
>     2. Windows 里 Obsidian 自动在新的库创建了 Welcome.md 文件。
> 
>     3. Windows 创建文件夹 testfolder1 ，文件夹里创建文件 testfolder1/testfile1.md，随便写点东西
> 
>     4. Windows 安装 remotely save
> 
>     5. Windows 设置 webdav。我用 infinicloud。**不要修改其他任何设置！！！**不设置密码，不设置自动运行，删除目的地默认是系统回收站。
> 
>     6. Windows 触发同步。
> 
> 
> 
> 2. infinicloud 网站
> 
> 
> 
>     1. 去 infinicloud 网站，检查 testvault文件夹是否有生成，testvault/testfolder1 文件夹是否有生成，testvault/testfolder1/testfile1.md 是否有生成，testvault/Welcome.md 是否有生成。期待行为是所有都生成了。
> 
> 
> 
> 3. iphone
> 
>     1. 打开 iphone Obsidian，创建新的 vault，名字叫 testvault
> 
>     2. iphone Obsidian 自动在新的库创建了 Welcome.md 文件。
> 
>     3. iphone obsidian 安装 remotely save
> 
>     4. iphone obsidian 设置 webdav。我用 infinicloud。**不要修改其他任何设置！！！**不设置密码，不设置自动运行，删除目的地默认是系统回收站。
> 
>     5. iphone 触发同步
> 
>     6. 检查 iphone obsidian 的 valut 内是不是生成了：testfolder1 文件夹，testfolder1/testfile1.md 文件，Welcome.md 文件
> 
> 
> 
> 4. windows
> 
>     1. windows ，删除 testfolder1 文件夹
> 
>     2. windows 触发同步
> 
>     3. windows 应该触发了保护，同步失败
> 
>     4. windows 的 remotely save 设置，修改删除保护为 100%，也即，去除保护
> 
>     5. windows 触发同步
> 
>     6. 这时候应该同步成功了
> 
> 
> 
> 5. infinicloud 网站
> 
>     1. 去 infinicloud 网站，**检查 testvault/testfolder1 文件夹是不是已经被删除了**，期待行为是被删除了
> 
> 
> 
> 6. iphone
> 
>     1. iphone 触发同步
> 
>     2. iphone 应该触发了保护，同步失败
> 
>     3. iphone 的 remotely save 设置，修改删除保护为 100%，也即，去除保护
> 
>     4. iphone 触发同步
> 
>     5. 这时候应该同步成功了
> 
>     6. 检查 iphone obsidian 的 **vault 内的 testfolder1 是不是被删除了**，期待行为是被删除了。

@2019YKL **精确按照**这里操作，除了 webdav 换成 s3 之外，其他步骤**精确按照**每一步进行，看有没有问题。求求了，不这样**精确按照步骤**进行测试的话，我们都是在浪费时间，查不出来的。

**Comment by nallebrean** [comment] 2024-05-06 10:16
My created test note on windows will be created in the vaults root and not
in the testdir1. I have to move it unless I change settings in Obsidan.
Does it matter?

Den mån 6 maj 2024 12:11fyears ***@***.***> skrev:

**Comment by 2019YKL** [comment] 2024-05-06 11:16
我多次重新按你的步骤执行了，与预期行为是一致的，但不稳定。

Ipad那边几率出现不删文件，并同步Mac已经删除的文件上去。

我测试了三组，表现不一致。

这次我ipad和mac都录屏下来了。

Mac录屏

https://github.com/remotely-save/remotely-save/assets/51532948/64071046-cd19-4971-84d5-f629136766e5

ipad录屏


https://github.com/remotely-save/remotely-save/assets/51532948/93209955-f813-430f-875a-ef3229081c90

**Comment by fyears** [comment] 2024-05-06 12:30
出错的那次导出一下同步记录？

**Comment by 2019YKL** [comment] 2024-05-06 12:32
> 出错的那次导出一下同步记录？

最近五次的同步记录

```
{
  "Welcome.md": {
    "key": "Welcome.md",
    "remote": {
      "key": "Welcome.md",
      "keyRaw": "Welcome.md",
      "mtimeSvr": 1714993171000,
      "mtimeCli": 1714993171000,
      "sizeRaw": 4,
      "size": 4,
      "etag": "\"81DC9BDB52D04DC20036DBD8313ED055\"",
      "synthesizedFolder": false,
      "keyEnc": "Welcome.md",
      "sizeEnc": 4,
      "mtimeCliFmt": "2024-05-06T18:59:31+08:00",
      "mtimeSvrFmt": "2024-05-06T18:59:31+08:00"
    },
    "prevSync": {
      "key": "Welcome.md",
      "keyRaw": "Welcome.md",
      "mtimeSvr": 1714993171000,
      "mtimeCli": 1714993171000,
      "sizeRaw": 4,
      "size": 4,
      "etag": "\"81DC9BDB52D04DC20036DBD8313ED055\"",
      "synthesizedFolder": false,
      "keyEnc": "Welcome.md",
      "sizeEnc": 4,
      "mtimeCliFmt": "2024-05-06T18:59:31+08:00",
      "mtimeSvrFmt": "2024-05-06T18:59:31+08:00"
    },
    "local": {
      "key": "Welcome.md",
      "keyRaw": "Welcome.md",
      "mtimeCli": 1714991246000,
      "mtimeSvr": 1714991246000,
      "size": 4,
      "sizeRaw": 4,
      "mtimeCliFmt": "2024-05-06T18:27:26+08:00",
      "mtimeSvrFmt": "2024-05-06T18:27:26+08:00",
      "keyEnc": "Welcome.md",
      "sizeEnc": 4
    },
    "decisionBranch": 10,
    "decision": "local_is_modified_then_push"
  },
  "testfolder/testfile.md": {
    "key": "testfolder/testfile.md",
    "remote": {
      "key": "testfolder/testfile.md",
      "keyRaw": "testfolder/testfile.md",
      "mtimeSvr": 1714993183000,
      "mtimeCli": 1714993183000,
      "sizeRaw": 9,
      "size": 9,
      "etag": "\"25F9E794323B453885F5181F1B624D0B\"",
      "synthesizedFolder": false,
      "keyEnc": "testfolder/testfile.md",
      "sizeEnc": 9,
      "mtimeCliFmt": "2024-05-06T18:59:43+08:00",
      "mtimeSvrFmt": "2024-05-06T18:59:43+08:00"
    },
    "decisionBranch": 3,
    "decision": "remote_is_created_then_pull"
  },
  "testfolder/": {
    "key": "testfolder/",
    "remote": {
      "key": "testfolder/",
      "keyRaw": "testfolder/",
      "size": 0,
      "sizeRaw": 0,
      "sizeEnc": 0,
      "mtimeSvr": 1714993183000,
      "mtimeSvrFmt": "2024-05-06T18:59:43+08:00",
      "mtimeCli": 1714993183000,
      "mtimeCliFmt": "2024-05-06T18:59:43+08:00",
      "synthesizedFolder": true,
      "keyEnc": "testfolder/"
    },
    "decisionBranch": 103,
    "decision": "folder_existed_remote_then_also_create_local"
  },
  "/$@meta": {
    "key": "/$@meta",
    "sideNotes": {
      "version": "2024047 fs version",
      "generateTime": 1714993191557,
      "generateTimeFmt": "2024-05-06T18:59:51+08:00"
    }
  }
}
```

**Comment by fyears** [comment] 2024-05-06 16:10
I fixed a bug around s3 in 0.4.20. May be it's relevant

**Comment by 2019YKL** [comment] 2024-05-06 16:15
> I fixed a bug around s3 in 0.4.20. May be it's relevant

问题似乎被成功解决了，多次测试多端写入/删除文件，问题没有再复现。

感谢你的付出～

**Comment by nallebrean** [comment] 2024-05-06 16:34
I stress tested on my first 'devTest' vault with the new version .20 and some of the deleted files are still coming back.

**Comment by fyears** [comment] 2024-05-06 16:53
> I stress tested on my first 'devTest' vault with the new version .20 and some of the deleted files are still coming back, using OneDrive

any hints? can you reproduce the error using my steps?

**Comment by nallebrean** [comment] 2024-05-06 16:53
I just tried on my Android phone, instead of iphone, but I don't get any
Welcome.md when I create 'testvault'.

Den mån 6 maj 2024 kl 18:15 skrev JK2333 ***@***.***>:

**Comment by fyears** [comment] 2024-05-06 16:55
never mind you can manually create it and write something (cannot be empty). the spirit is that your vault cannot be empty even after you delete testfolder

**Comment by fyears** [comment] 2024-05-06 17:21
does your android have any files? but anyways it's not relevant with deletions, so let's disable the protection and let it sync then reenable the protection

**Comment by nallebrean** [comment] 2024-05-06 17:36
"does your android have any files?" Only my manually created Welcome.md.

Everything when as expected. Now I will try with OneDrive.

**Comment by nallebrean** [comment] 2024-05-06 18:42
now I seams to have synced an empty file from windows to the Andriod. That should not happend because onedrive didnt accept that. 

I then created several empty files in windows but got rejected because they where empty. But the folder "testdir6" that contain them were created.

**Comment by fyears** [comment] 2024-05-06 18:53
@nallebrean 

really the only thing we both want to find out, is "how to consistently reproduce the error that deleted folders coming back". 

so i wrote the steps and hopefully any one can find out anything not running as my description. 

please, please, please, try to strictly follow my steps to find out anything abnormal, any deleted folders coming back.

empty files should not be synced, please do not create empty files to make things more complicated. please try to focus on the original problem.

**Comment by fyears** [comment] 2024-05-06 18:54
> I then created several empty files in windows but got rejected because they where empty. But the folder "testdir6" that contain them were created.

that's expected, and they are not relevant to the original problem of the current issue

**Comment by fyears** [comment] 2024-05-06 19:12
please, don't randomly try, don't randomly guess, don't randomly do something not relavent, just try to **precisely follow the step** and see any thing goes wrong. **precisely**, **step by step**, do not do any other thing, no need to do more tests, do not messy up with the database.

i really want to help, but i am really unable to guess what happen if the steps are not the same as my guides.


1. windows, android, onedrive
    1. on windows, delete testvault because it's useless now and we want to reset everything
    2. on android, delete testvault because it's useless now and we want to reset everything
    3. on onedrive website, delete `/Apps/remotely-save/testvault` because it's useless now and we want to reset everything

2. Windows
    1. On Windows, create new vault naming "testvault2". notice, we named it testvault**2** to avoid anything relavent to the previous testvault
    2. On Windows, Obsidian should create a default file "Welcome.md". if not, create the file manually, **and write something into it so that it's not empty**.
    3. On Windows, create new folder "testfolder1", create new file inside the folder "testfolder1/testfile1.md". Write something into that md file so that it's not empty
    4. On Windows, install remotely save
    5. On Windows, auth onedrive. DO NOT TOUCH any other settings!!!! No setting password, not setting auto run, and deletion destination by default should be system trash.
    6. On Windows, sync

3. onederive website
    1. go to onederive website, check these are generated **inside `/Apps/remotely-save/`**: folder testvault2, folder testvault2/testfolder1, file testvault2/testfolder1/testfile1.md, file testvault/Welcome.md. The expected behaviour is that all of them are generated.

4. android
    1. On android, create new vault naming "testvault2". notice, we named it testvault**2** to avoid anything relavent to the previous testvault
    2. On android, Obsidian should create a default file "Welcome.md". if not, create the file manually, **and write something into it so that it's not empty**.
    3. On android, install remotely save
    4. On android, auth onedrive. DO NOT TOUCH any other settings!!!! No setting password, not setting auto run, and deletion destination by default should be system trash.
    5. On android, sync
    6. On android, check all these are generated in the vault: folder testfolder1, file testfolder1/testfile1.md, file Welcome.md. The expected behaviour is that all of them are generated.

5. windows
    1. On Windows, delete the folder testfolder1
    2. On Windows, sync
    3. On Windows, the sync should fail, because of the deletion protection
    4. On Windows, change the remotely save settings "Abort Sync If Modifications Above Percentage" to "100% (disable the protection)".
    5. On Windows, sync
    6. The sync should succeed.

6. onederive website
    1. go to onederive website, **check these are deleted or not inside `/Apps/remotely-save/`: folder testvault2/testfolder1 and file testvault2/testfolder1/testfile1.md**. The expected behaviour is that all of them are deleted.

7. android
    1. On android, sync
    2. On android, the sync should fail, because of the deletion protection
    3. On android, change the remotely save settings "Abort Sync If Modifications Above Percentage" to "100% (disable the protection)".
    4. On android, sync
    5. The sync should succeed.
    6. On android:  **check these are deleted or not: folder testfolder1 and file testfolder1/testfile1.md**. The expected behaviour is that all of them are deleted.

**Comment by nallebrean** [comment] 2024-05-06 19:26
> @nallebrean
> 
> really the only thing we both want to find out, is "how to consistently reproduce the error that deleted folders coming back".
> 
> so i wrote the steps and hopefully any one can find out anything not running as my description.
> 
> please, please, please, try to strictly follow my steps to find out anything abnormal, any deleted folders coming back.
> 
> empty files should not be synced, please do not create empty files to make things more complicated. please try to focus on the original problem.

As mentioned I followed the script with onedrive and it worked and it use to work with a small number of files. 

The problem with reappearing files has been with syncing changing of a large number of files in the hundreds. I found it very unlikely to recreate the bug with just 1 file and 1 folder because that is not where the bug appears to me. Of course I then try many files when the small file test succeed. And then a empty file appeared from nowhere, related or not.

**Comment by nallebrean** [comment] 2024-05-06 20:58
4.vi, Fails, due to the protection. Next step?

**Comment by 2019YKL** [comment] 2024-05-07 00:09
> 4.vi, Fails, due to the protection. Next step?4.vi，由于保护而失败。下一步？

Turn off protection in the settings first, and have you updated to the latest version of the plugin?

![CleanShot 2024-05-07 at 08 08 36@2x](https://github.com/remotely-save/remotely-save/assets/51532948/e202f851-33da-4049-b47e-bae429475599)****

**Comment by fyears** [comment] 2024-05-07 02:04
> 4.vi, Fails, due to the protection. Next step?

ok, let's add a step "4.vi.2 disable the protection" right after 4.vi, and continue the steps

**Comment by nallebrean** [comment] 2024-05-07 08:02
To be totally clear, the new of disable protection step will not be 4.6.2
but 4.4.2?

Den tis 7 maj 2024 04:05fyears ***@***.***> skrev:

**Comment by fyears** [comment] 2024-05-07 10:28
in test vault, every time you meet protection, just add an extra step to disable the protection

**Comment by nallebrean** [comment] 2024-05-07 10:46
I have made the full test and everything went as expected. 7.2 och 7.3 7.4 where skipped because the protection was deactivated in 4.4.2.

**Comment by fyears** [comment] 2024-05-07 15:25
So obviously unfortunately the issue cannot be reproduced in a simple way.      :-(        :-(

we should try some testing to find out the key point to stably trigger the bug... but i have no clues yet

**Comment by nallebrean** [comment] 2024-05-07 15:37
Maybe trying different number of many files? 10/50/100/200/... Files?



Den tis 7 maj 2024 17:26fyears ***@***.***> skrev:

**Comment by 2019YKL** [comment] 2024-05-08 00:48
请问现在可以开启自动同步的选项了么

**Comment by fyears** [comment] 2024-05-08 02:00
开呗

**Comment by nallebrean** [comment] 2024-05-09 22:06
I follow the instruction with following added step. 
2.1 Another name.
2.3.1 Close obsidian.
2.3.2. open vault mapp and dubblicate the testfil1.md to 500 files.
2.3.3 Open the vault again and the files should be loaded. 
4.2 Accidently named it with .md.md so there is two files in 4.6. 

Error 
7.6 All files are note deleted from obsidan. 

Generated an export, changed the namn on the mapp and synced android and then windows. The non deleted files where of course created in windows. 
[sync_plans_hist_exported_on_1715291313199.md](https://github.com/remotely-save/remotely-save/files/15268125/sync_plans_hist_exported_on_1715291313199.md)

![image](https://github.com/remotely-save/remotely-save/assets/152818581/66b3ee03-cbff-4a39-a249-8c73c609fbb3)

export from andriod. 
[sync_plans_hist_exported_on_1715291313199.md](https://github.com/remotely-save/remotely-save/files/15268127/sync_plans_hist_exported_on_1715291313199.md)

**Comment by fyears** [comment] 2024-05-10 00:03
two files you uploaded are the same.

and what is "mapp"?

**Comment by nallebrean** [comment] 2024-05-10 06:20
I don't know why the file got there twice... Do you want the windows export
too?

Sorry "mapp" (Swedish) = folder.



Den fre 10 maj 2024 02:03fyears ***@***.***> skrev:

**Comment by nallebrean** [comment] 2024-05-10 09:40
[win sync_plans_hist_exported_on_1715333863494.md](https://github.com/remotely-save/remotely-save/files/15273249/win.sync_plans_hist_exported_on_1715333863494.md)

Well, there is the export file from windows if you have use of it.

**Comment by fyears** [comment] 2024-06-16 11:55
Admittedly the bug cannot be reproduced on my side. 

However, I have improved the sync algorithm a little bit this month and fixed some bugs. Hopefully the problem doesn't exist any more. So I close this issue for this moment.

**If anyone can provide reproducible steps**, please feel free to re open the issue or create a new issue. **Reproducible steps are really needed** otherwise I cannot investigate the bug...

**Closed by fyears** 2024-06-16 11:55 UTC
Labels: bug

**Comment by Striwx** [comment] 2025-10-08 14:08
Hello there, 

i just had the same issue on macOS 13.6 and the fix i've found was to empty the system trash once i deleted the files in Obsidian (with "Deletion Destination" set to "system default (default)").

It seems the problem comes from macOS for me, i used Obsidian on my iPad, iPhone and Windows several days before without any issue. I use the last version of the plugin with Dropbox along with the last version of Obsidian.
