### ISSUE TITLE
[Bug]: If enable .obsidian sync, ".obsidian/plugins/ Invalid response: 405 Method not allowed" reported

### ISSUE THREAD

**Issue by duaka** [remotely-save/remotely-save#96] opened 2022-04-26 08:17 UTC
### What happened?

If enable .obsidian sync, ".obsidian/plugins/ Invalid response: 405 Method not allowed" reported.
If disable it, sync completed.

Nginx log:
`MKCOL /notebook/.obsidian/plugins/ HTTP/1.1" 405 568 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) obsidian/0.14.6 Chrome/100.0.4896.75 Electron/18.0.4 Safari/537.36"`

Nginx conf:
```
dav_methods PUT DELETE MKCOL COPY MOVE;
dav_ext_methods PROPFIND OPTIONS;
dav_access  user:rw group:rw all:r;

client_max_body_size    500M;
create_full_put_path    on;
client_body_temp_path   /tmp/;
```

### What OS are you using?

Windows, Linux

### What remote cloud services are you using?

webdav

### Version of the plugin

0.3.19

### Version of Obsidian

0.14.6

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by duaka** [comment] 2022-04-26 08:51
from nginx error log:
`[error] 3209389#3209389: *3 mkdir() "/aka/NOTEBOOK//.obsidian/plugins" failed (17: File exists), ... request: "MKCOL /notebook/.obsidian/plugins/ HTTP/1.1"`

It seems remotely-save will create plugins directory regardless of whether it exists or not.

**Comment by fyears** [comment] 2022-04-27 05:09
duplicate of https://github.com/remotely-save/remotely-save/issues/81

it seems to be an issue on nginx side.

one workaround is that using encryption mode of remotely save

**Closed by fyears** 2022-04-27 05:09 UTC
Labels: bug
