### ISSUE TITLE
[Bug]: OneDrive Personal on Android gets stuck on auth

### ISSUE THREAD

**Issue by acronid** [remotely-save/remotely-save#417] opened 2024-01-04 12:00 UTC
### What happened?

Yesterday Remotely Save asked me to re-auth on both PC and Mobile.
PC re-auth worked without problems.
But on Mobile (Android) it gets endlessly stuck on "Connecting to OneDrive" modal after I approve the auth request in browser.
Tried reinstalling the plugin, but it didn't help.

### What OS are you using?

Android

### What remote cloud services are you using?

OneDrive for personal

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment] 2024-01-04 14:11
that's strange... nothing goes changes...i will try to reproduce the problem in weekend.

if you are hurry and want to work around, you could simplify copy the data.json from pc to your android mobile.

**Comment by fyears** [comment] 2024-01-04 14:12
and do u use any proxy may be?

**Comment by fyears** [comment] 2024-01-04 14:15
and r u referring this page?  ![image](https://github.com/remotely-save/remotely-save/assets/1142836/ce74a42f-76dc-4a9e-b78b-6012e517d73e)

**Comment by acronid** [comment] 2024-01-04 16:01
- I'm not in a hurry atm, no worries. But thank you for the advise about data.json, I will try this.
- I'm not using any proxy.
- Yes, this page that you sent the screenshot of. It just stays on it and doesn't progress further. I tried waiting for ~30 mins, but it was still on this "Connecting to OneDrive" page.

**Comment by acronid** [comment] 2024-01-04 17:47
Okay, I tried copying data.json from PC to Mobile.
- It showed me that I'm connected under my account name, all good (Pic 01)
- But then when I pressed "Check connectivity" it gave me "We can not connect to OneDrive. Request failed, status 400" (Pic 02)
- Then I tried running sync from the command palette and it gave me same status 400 and "error while getting_remote_files_list" message.

![%pn_2024-01-04_20-27-35](https://github.com/remotely-save/remotely-save/assets/31851007/7f2ee9a0-1759-4b9b-8e8a-500f99a3e40e)
![photo_2024-01-04_20-28-29](https://github.com/remotely-save/remotely-save/assets/31851007/06eeb308-dd6a-4d27-bbe6-5b702463d6d0)

**Comment by fyears** [comment] 2024-01-05 18:12
i sincerely have no idea what's going on, especially when, you know, your pc works without problem...

the username is just saved in data.json so it doesn't mean you are connected to onedrive on android.

how about this way, if you'd like to:

1. backup your important data, what ever what's in your pc, mobile, onedrive app folder
2. backup your pc's working data.json
3. go to https://www.microsoft.com/consent and delete remotely-save. attention that it also makes your pc requring reauth again later.
4. on your android click revoke button.
5. on your android delete the data.json to reset anything.
6. on your android try to connect again!
7. and on your pc try to connect again, which you know should be ok.

the main point above is that really resetting everything on microsoft's side.

**Comment by acronid** [comment] 2024-01-05 19:38
Tried what you suggested, step by step.
Android still is getting stuck on "Connecting to OneDrive". PC Win was fine.
Decided to try if I can maybe use Dropbox instead. But to my surprise Android was also getting stuck on "Connecting to Dropbox" after I gave access permission.

I suppose there's something wrong with my phone in this case, even though I have no idea what exactly. Everything was syncing perfectly up until Jan 2nd. And I didn't change anything.
Gonna see if I can figure something out.

Either way, thank you for your help!

**Comment by fyears** [comment] 2024-01-06 02:37
ok, wish u best luck!

and i could auth without problem on my android. so the issue is closed by now. if you suspect something or find out some clues, feel free to re open the issue

**Closed by fyears** 2024-01-06 02:37 UTC
Labels: bug

**Comment by BiltuDas1** [comment] 2024-02-18 06:42
I also faced the same issue for few weeks, I did the below steps to solve the problem

- On Android, I took copy of the Obsidian vault, and then clear data of the Obsidian App from the Phone Settings
- Then I opened the Obsidian and create a new Vault, and then I head over to the Community Plugins and installed Remotely Save
- Now I authenticate Remotely Save with OneDrive (During this operation I was using a VPN cause my ISP blocks Obsidian Community plugins)
- The authentication happens normally, now I go to the vault folder and then copied .obsidian/plugins/remotely-save folder and replace the contents with the previous vault's .obsidian/plugins/remotely-save folder
- Now again I clear the data of the Obsidian App and then I opened the old Vault in Obsidian, and the problem is solved.
