### ISSUE TITLE
[Bug]: OneDrive iOS sync is much slower than windows

### ISSUE THREAD

**Issue by CVL7** [remotely-save/remotely-save#644] opened 2024-05-05 09:53 UTC
### What happened?

Syncing on iOS takes about 2 minutes, while on windows it takes only several seconds.

Vault is about 1k files with overall size of 300mb
I am using RClone Crypt. All other settings are default. Changing concurrency setting doesn't seem to effect anything. Same Wi-Fi connection.

Windows 11 sync profiler export:
```
[startTime]: 2024-05-05T11:37:44+02:00
[start big sync func]: start
[finish step2 (list partial remote and check password)]: 3494.8ms
[finish step3 (list remote)]: 285.2ms
  [enter walk for local]: 0ms
  [finish getting walk for local]: 0.1ms
  [finish transforming walk for local]: 0.3ms
  [finish walk for local]: 0ms
[finish step4 (list local)]: 0ms
[finish step5 (prev sync)]: 25.6ms
  [ensembleMixedEnties: enter]: 0ms
  [ensembleMixedEnties: finish remote]: 11ms
  [ensembleMixedEnties: finish prevSync]: 16.1ms
  [ensembleMixedEnties: finish local]: 12.2ms
  [ensembleMixedEnties: exit]: 0ms
[finish step6 (build partial mixedEntity)]: 0.1ms
  [getSyncPlanInplace: enter]: 0ms
  [getSyncPlanInplace: finish sorting]: 0.3ms
  [getSyncPlanInplace: finish looping]: 0.9ms
  [getSyncPlanInplace: exit]: 0ms
[finish building full sync plan]: 0.1ms
[finish writing sync plan]: 23.3ms
[finish step6 (make plan)]: 0ms
  [doActualSync: enter]: 0ms
  [doActualSync: finish splitting steps]: 0.9ms
    [doActualSync: step 0 start]: 0ms
    [doActualSync: step 0 end]: 11.5ms
    [doActualSync: step 1 start]: 0ms
    [doActualSync: step 1 end]: 0.1ms
    [doActualSync: step 2 start]: 0ms
    [doActualSync: step 2 end]: 0ms
    [doActualSync: step 3 start]: 0ms
    [doActualSync: step 3 end]: 873.8ms
  [doActualSync: exit]: 0ms
[finish step7 (actual sync)]: 0ms
[finish syncRun]: 0ms
```

iPhone 13, iOS 17.4.1 sync profiler export:
```
[startTime]: 2024-05-05T11:35:33+02:00
[start big sync func]: start
[finish step2 (list partial remote and check password)]: 4582ms
[finish step3 (list remote)]: 94238ms
  [enter walk for local]: 0ms
  [finish getting walk for local]: 1ms
  [finish transforming walk for local]: 0ms
  [finish walk for local]: 0ms
[finish step4 (list local)]: 0ms
[finish step5 (prev sync)]: 193ms
  [ensembleMixedEnties: enter]: 0ms
  [ensembleMixedEnties: finish remote]: 8ms
  [ensembleMixedEnties: finish prevSync]: 10ms
  [ensembleMixedEnties: finish local]: 11ms
  [ensembleMixedEnties: exit]: 0ms
[finish step6 (build partial mixedEntity)]: 0ms
  [getSyncPlanInplace: enter]: 1ms
  [getSyncPlanInplace: finish sorting]: 0ms
  [getSyncPlanInplace: finish looping]: 0ms
  [getSyncPlanInplace: exit]: 0ms
[finish building full sync plan]: 10ms
[finish writing sync plan]: 19ms
[finish step6 (make plan)]: 0ms
  [doActualSync: enter]: 4ms
  [doActualSync: finish splitting steps]: 1ms
    [doActualSync: step 0 start]: 0ms
    [doActualSync: step 0 end]: 5ms
    [doActualSync: step 1 start]: 0ms
    [doActualSync: step 1 end]: 0ms
    [doActualSync: step 2 start]: 0ms
    [doActualSync: step 2 end]: 0ms
    [doActualSync: step 3 start]: 0ms
    [doActualSync: step 3 end]: 0ms
  [doActualSync: exit]: 0ms
[finish step7 (actual sync)]: 0ms
[finish syncRun]: 0ms
```

Is there any good reason for (list remote) to be x300 slower on iOS, or is it a bug?

### What OS are you using?

Windows, iOS (iPhone, iPad)

### What remote cloud services are you using? (Please choose the specified one if it's in the list)

OneDrive for personal

### Version of the plugin

0.4.19

### Version of Obsidian

1.5.12

### Using password or not

- [X] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by CVL7** [comment] 2024-05-05 10:24
After some testing it seems the sync time increases after every sync. Resetting the plugin brings sync time down to 8s for the first sync, 30s for the second, 50s for the third.

**Comment by fyears** [comment] 2024-05-05 13:16
listing remote is basically blindingly calling the api of onedrive: https://github.com/remotely-save/remotely-save/blob/757eb5c80162b8f75207b627d6bc457868fbe2d5/src/fsOnedrive.ts#L659

and the plugin doesn't remember previous call's result.

thus:

1. I expect no difference about network steps on any deivce... But after getting the data the device needs to convert them into internal data structure which might be affected by device's performance 
2. I expect no difference about calling the api multiple times.

> Is there any good reason for (list remote) to be x300 slower on iOS, or is it a bug?

really no idea yet. but let me construct a test vault as many files as yours and do some test


> Resetting the plugin got sync time down to 8s for the first sync, 30s for the second, 50s for the third.

Do you run profiler each time? can you verify the time consiming cost in each step?

**Comment by CVL7** [comment] 2024-05-05 21:52
> Do you run profiler each time? can you verify the time consiming cost in each step?
I think it was a random thing that just looked suspicious, I could not reproduce it now.

(list remote) now takes completely random times on iOS. Sometimes it takes 8s, other times the whole minute. Testing it right in front of PC, where it always takes 300ms now on sync without any changes. I test it back and forth in case microsoft has some rate limits, but PC is always consistent and very fast on that step. Maybe some weird microsoft thing or some weird thing somewhere in my setup? I was also testing it on mobile internet and results are the same.. Anyways that waiting time is not really a dealbreaker for me. Other than that plugin works great and I really enjoy using it.

Let me know if there is anything I can do to help you debug the issue. But if nobody else experience the slowdown, I guess it's fair to say that its just some ghost on my side and we can close the issue ;)

**Comment by fyears** [comment] 2024-05-08 15:01
Hi, I believe I know what happen now.

```
[finish step2 (list partial remote and check password)]: 4582ms
[finish step3 (list remote)]: 94238ms
```

The key point is not calling onedrive, but the steps of encryption and decryption behind step3: 94238ms.

The plugin uses devices' cpu to do the encryption and decryption, and iphone is of course significantly slower than pc.

So it's not a bug, but a prize you have to afford for security.

Unfortunately I don't know how to fix that by now. (Maybe it's impossible???) So let me close the issue now. Thanks for your detailed report though.

**Closed by fyears** 2024-05-08 15:01 UTC
Labels: bug

**Comment by gzz2000** [comment] 2025-03-16 06:26
(I found the maintainers are able to read chinese so I will post it directly in chinese. You can use google translate if you use english.)

我遇到了很类似的情况，用了onedrivefull和rclone，今天仔细调试了一下。在ios越狱设备上观察，有如下发现：

1. walk很快就完成了，不是远端的问题。问题出在fsEncrypt _dealWithWalk，这个速度非常不稳定，很多时候会直接消耗几分钟。
2. _dealWithWalk的时候，理论上cpu应该打满用于加解密，然而用CocoaTop看完全没有占用。

仔细读代码，我认为原因出在rclone加密策略使用了worker，而worker这东西直接被挂在了后台，调度的优先级太低。

**Comment by almogtzabari** [comment] 2025-06-18 15:39
If it helps, I also notice a significantly slower sync on iOS compared to my Windows and Mac machines (using backblaze b2).
