### ISSUE TITLE
[Bug]: An unfound folder can cause whole sync to abort

### ISSUE THREAD

**Issue by daledesilva** [remotely-save/remotely-save#406] opened 2023-12-18 12:12 UTC
### What happened?

I've found that a previous folder that existed in my vault that doesn't exist anymore keeps causing the syncs to be aborted.

I get this message
<img width="324" alt="image" src="https://github.com/remotely-save/remotely-save/assets/18710973/83fbf534-23c3-4046-9768-4a48c29e1645">

The folder "Ink" used to exist but I deleted it. This seems to cause the whole sync to be aborted.

Note:
I've deleted sync mappings, sync plan history, and reset local internal cache (and obsidian), but the error persists.
However, by recreating the folder on each device, then syncing them both, the error went away, after that, I deleted the folder on one device and synced it to the other and the error didn't come back.

UPDATE: This didn't fix the issue. After recreating the folder on each device, syncing them all, and then deleting the folder again. The issue comes back preventing syncing.

### What OS are you using?

MacOS, iOS (iPhone, iPad)

### What remote cloud services are you using?

Dropbox

### Version of the plugin

0.3.25

### Version of Obsidian

1.4.16

### Using password or not

- [ ] Yes.

### Ensure no sensitive information

- [X] I ensure that no sensitive information is submitted in the issue.

**Comment by fyears** [comment] 2024-01-05 00:19
would you liketo delete the file _remotely-save-metadata-on-remote.{json,bin} on your remote service and try again? it seems that the logic goes into an unexpected branch, which i still don't understand how to reproduce

**Comment by daledesilva** [comment] 2024-01-06 06:23
This just happened again to me and so I deleted that file and it fixed it.

In terms of reproduction, I _think_ the following is true...

I've noticed that it mostly happens based on folder name casing.
It's quite common for me to create a folder on my iPad or iPhone, which syncs while I'm working in it.
Then, I realise that it has inconsistent capitalisation, so I fix it. Then, when it syncs again, it pulls the old folder back so now I have two folders with different casing. So I delete the old one and when it syncs again it seems to get confused in this way.
Related to: https://github.com/remotely-save/remotely-save/issues/407

However, even if this error can't be ironed out perfectly, the big issue here seems simpler to me. Which is that it shouldn't abort the whole sync simply because it's lost track of a folder. It should just skip that folder.
ie. The folder isn't on remote or local anymore, so clearly nothing can be done, so at least sync the other files.

Of course, it could still display a notice, but even then, there's nothing the user can do about it, nor do they know why it was marked as kept (Because they didn't mark it kept), so it's just behind the scenes cleanup and correction that they don't need to know about and and can't make use of.

IMO. It should really just skip the folder silently.
But at the very least, skip and not abort.

**Comment by fyears** [comment] 2024-01-06 11:43
thanks for your steps to reproduce! i will try that...

the abortion comes from the point that the "must be kept" is some code branch i never thought anyone could run into, that indicates that my code has some minor bugs that i should fix instead of let it silently go away.

but ok i could consider let it go through if i could not find a solution. thanks for your suggestion

**Comment by daledesilva** [comment] 2024-01-06 13:15
Pretty good you thought of catching that code branch in the first place then! Great work and thanks for the plug-in!

**Comment by hk-github** [comment] 2024-01-07 05:04
I have had the very same issue recently.  
I also noticed that when I manually created the "missing" folder, it was impossible to get an error message saying that the folder already exists.  
I hope the issue will be fixed soon.  Thanks.

**Comment by fyears** [comment] 2024-01-07 07:38
@hk-github would you like to provide any reproducible steps?

**Comment by hk-github** [comment] 2024-01-07 16:24
My reproduction process is almost the same as Daledesilva's.
I have 1 iPhone and 3 iPads along with 2 PCs.  Deleting one of the Case-varied-but same-name folders caused the sync termination problem.

I have two folders: "Folder_01" and "folder_01".  I didn't like the duplication and fluctuation in the naming of folders, so I deleted one of them, for example, "folder_01," and the problem occurred.

I also noticed that this seems to be an IOS-related phenomenon.  I have these 2 folders on IOS devices, whereas I have only one folder on PCs.  As I commented earlier, when I try to create the other case-different folder on PC, there comes a "Destination file already exists" error message.

I hope my comment might be some help.

Oh, you have just released a new version (0.3.34).  I am still on the older version (0.3.25).  
Has this new version solved this issue?  I hope so.  Thanks.

**Comment by fyears** [comment] 2024-01-07 16:51
still not sorry, but as a clear reproduction step is provided hopefully i will figure out a way soon

**Comment by denis3509** [comment] 2024-01-18 05:46
it happened to me when i rename folder from 'Commands' to 'commands'. Now this error aborts sync, deleting  _remotely-save-metadata-on-remote.{json,bin} didn't help. Creating folder 'Commands' removed error but files from 'commands' keep copying to 'Commands'

**Comment by daledesilva** [comment] 2024-01-18 06:04
> it happened to me when i rename folder from 'Commands' to 'commands'. Now this error aborts sync, deleting _remotely-save-metadata-on-remote.{json,bin} didn't help. Creating folder 'Commands' removed error but files from 'commands' keep copying to 'Commands'
> 
> i am using dropbox to sync

I've also experienced this follow up problem you described, where you manage to get the folder named what you want, but then randomly files get moved to the folder of the old name.

**Comment by fyears** [comment] 2024-01-18 10:23
the main problem is that both windows and dropbox are case insensitive... i never thought of that before. i am thinking of a solution

**Comment by fyears** [comment] 2024-03-30 07:01
dup of https://github.com/remotely-save/remotely-save/issues/567 and fixed

**Closed by fyears** 2024-03-30 07:01 UTC
Labels: bug
